version: 2.1
orbs:
  node: circleci/node@3.0.0
  puppeteer: threetreeslight/puppeteer@0.1.2
jobs:
  build:
    docker:
      - image: circleci/node:10.16.0
        environment:
          NODE_ENV: development # Only needed if puppeteer is in `devDependencies`

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: npm test


