version: 2.1
orbs:
  node: circleci/node@3.0.0
  puppeteer: threetreeslight/puppeteer@0.1.2
jobs:
  build:
    docker:
      - image: circleci/node:12
        environment:
          NODE_ENV: development

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: npm test

